### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/root/Bot/dist/client/index.html'

### ISSUE THREAD

**Issue by SploeCyber** [AlexanderWyss/discord-bot-node#1]
I hope u fix this.

**Comment by AlexanderWyss** [comment]
Did you build the client?

**Comment by AlexanderWyss** [comment]
I added clearer instructions in the readme. Could you try again?

**Comment by SploeCyber** [comment]
doesn't work for me

**Comment by AlexanderWyss** [comment]
Can you provide some more information?

**Comment by SploeCyber** [comment]
After build, it still shows the same problem.
Error: ENOENT: no such file or directory, stat '/app/dist/client/index.html'

**Comment by AlexanderWyss** [comment]
Well mate i can't reproduce it. It works on my god damn machine.
Send me your node version, the exact commands you executed and any errors.

**Comment by SploeCyber** [comment]
My node version is v12.0.0

**Comment by SploeCyber** [comment]
https://hastebin.com/ifoyohezoc.coffeescript
Full Log

**Comment by AlexanderWyss** [comment]
Read the fucking readme.
You need to cd into the client folder and execute npm i & npm run build --prod before you can start the server.
